# Generated by Django 3.0.5 on 2020-08-29 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31)),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Variety',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31)),
            ],
        ),
        migrations.CreateModel(
            name='Mascot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31)),
                ('date_unveiled', models.DateField()),
                ('year_retired', models.DateField()),
                ('mhof_nominated_year', models.DateField()),
                ('mhof_inducted_date', models.DateField()),
                ('history', models.CharField(max_length=255)),
                ('student_pro', models.BooleanField()),
                ('image_file', models.ImageField(upload_to='mascots_portraits')),
                ('image_url', models.URLField()),
                ('character_type', models.CharField(choices=[('AC', 'Animal Character'), ('LA', 'Live Animal'), ('HC', 'Human Character'), ('LH', 'Live Human'), ('MC', 'Multiple Characters')], max_length=2)),
                ('selection_process', models.CharField(max_length=255)),
                ('performer_type', models.CharField(max_length=255)),
                ('website', models.URLField()),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mascots.Maker')),
                ('sub_veriety', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sub_variety', to='mascots.Variety')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teams.Team')),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variety', to='mascots.Variety')),
            ],
        ),
    ]
